In [1]:
import Attaxx
import Go
import numpy as np
from ioannina import *
from go.inputconverter import gen_batch
import avaliar

pygame 2.1.2 (SDL 2.0.18, Python 3.10.0)
Hello from the pygame community. https://www.pygame.org/contribute.html


array([9.99758455e-01, 1.58915265e-08, 2.41528638e-04])

## Attaxx

In [4]:
game=avaliar.makegame('G7x7')

In [5]:
rede=Neura(game)
rede.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 7, 7, 17)]   0           []                               
                                                                                                  
 conv2d (Conv2D)                (None, 7, 7, 84)     12936       ['input_1[0][0]']                
                                                                                                  
 batch_normalization (BatchNorm  (None, 7, 7, 84)    336         ['conv2d[0][0]']                 
 alization)                                                                                       
                                                                                                  
 activation (Activation)        (None, 7, 7, 84)     0           ['batch_normalization[0][0]']

In [12]:
arr=gen_batch(game)
np.array([arr]).shape

(1, 7, 7, 17)

In [13]:
p,v=rede.net.predict(np.array([arr]),batch_size=1)

In [ ]:
print(p)

In [ ]:
print(v)

## Go

In [ ]:
go=Go.main()
go=go.move((0,0))

In [ ]:
arr=gen_batch(game)
np.shape(arr)

In [ ]:
redeg=Neura(go)
redeg.summary()

In [ ]:
p,v=rede.net.predict(np.array([arr]),batch_size=1)

In [ ]:
print(p)

In [ ]:
print(v)

In [1]:
import Attaxx
import Go
import numpy as np
from ioannina import *
from go.inputconverter import gen_batch
import tensorflow as tf
import optimizar,avaliar
import MCTS

pygame 2.1.2 (SDL 2.0.18, Python 3.10.0)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
game=avaliar.makegame('G7x7')

In [3]:
rede=Neura(game,get_best_name(game))
rede.compilar()

In [4]:
ARGS = {
    'cpuct': 1.5,
    'num_searches': 100
}
alpha=MCTS.MCTS(game,ARGS,rede)

In [5]:
avaliar.agent_v_agent(game,alpha,alpha)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 

KeyboardInterrupt: 